### ISSUE TITLE
serverless-offline-sqs incompatible with new versions of serverless-offline

### ISSUE THREAD

**Issue by BenHili** [CoorpAcademy/serverless-plugins#116]
When installing alongside newer versions of serverless-offline this line:

`const LambdaContext = require('serverless-offline/src/LambdaContext');`

fails as LambdaContext doesn't exist on that path

**Comment by thetumper** [comment]
npm warns of the version requirement during install:

npm WARN serverless-offline-sqs@3.1.3 requires a peer of serverless-offline@^5.12.1 but none is installed. You must install peer dependencies yourself.

**Comment by bakasmarius** [comment]
`serverless-offline` is now version 6.1.0 - any plans on supporting v6?
I'm stuck with v6.0.0-alpha.8, any newer version throws this error:
`Error: Cannot find module 'serverless-offline/src/functionHelper'`

This commit might be worth looking into: https://github.com/dherault/serverless-offline/commit/85e0c2c13dcafde2d3924e807a53174d9398faca

**Comment by vuk** [comment]
I have the same issue. Has anyone picked this up? If not, would it be ok if I tried?

**Comment by Deliverart** [comment]
Any news on the @bakasmarius issue?
I have the same problem!

**Comment by oguimbal** [comment]
**+1**

I tried to investigate... but it turns out that this is not an easy fix without any prior knowledge. `serverless-offline` has changed quite a bit since 6.0.0-alpha.8.

**Some details**:  Several plugins of this repo (I use `serverless-offline-sqs` and `serverless-offline-dynamodb-streams`) are using nasty internal functions of `serverless-offline` to trigger lambda processing, but these functions do not exist anymore. The core model of `serverles-offline` has changed dramatically. The commit referenced by @bakasmarius  was just moving the incriminated functions, but they have now disapeared completely.

**Wokaround** (kind of): Use `serverless-offline@6.0.0-alpha.8` :/ 
nb: This version required (for me) a nasty fix in `node_modules\serverless-offline-dynamodb-streams\src\index.js` - I had to invert `functionName` and `__function` arguments, at line 95 & 96.

**Comment by christophersbarrett** [comment]
Has anyone brought this package up to date locally that they could potentially create a PR for? :-D :-D

**Comment by esetnik** [comment]
@christophersbarrett I have a workaround that's working and i'm pushing up a PR today.

**Comment by bakasmarius** [comment]
@esetnik thanks!! I'll try to find some time this week to check your PR locally, no promises though 😬

**Comment by bakasmarius** [comment]
@esetnik I couldn't get it to work, left a [comment](https://github.com/CoorpAcademy/serverless-plugins/pull/125/files#r419513506) in your PR

**Comment by AdrieanKhisbe** [comment]
Handled by #129, hence closing
