### ISSUE TITLE
SQS trigger only once

### ISSUE THREAD

**Issue by jorgemarcondes** [CoorpAcademy/serverless-plugins#27]
When I run the command: 
`serverless offline start`
SQS is triggered only once, i need to restart serverless to trigger again.

**Comment by gemmadlou** [comment]
> I had the same issue with the included example. Try switching to a callback instead of returning a promise. The code that worked for me was:
> 
> ```
> module.exports.handler = (event, context, callback) => {
>   console.log(JSON.stringify(event, null, 4));
>   callback();
> };
> ```

This would be great in the docs if it isn't already.

**Comment by godu** [comment]
@jorgemarcondes it's weird. Could you share a project to reproduce ?

It might be because of [promise/callback test](https://github.com/CoorpAcademy/serverless-plugins/blob/2a79dad29b194c544d2fe57ae1c92ca3b854d844/packages/serverless-offline-sqs/src/index.js#L145-L149)

I hope this [PR](https://github.com/CoorpAcademy/serverless-plugins/pull/50/commits/4b27d378ea8a586e398e9f19f8487f559d0c90e3) fix your problem.

**Comment by jorgemarcondes** [comment]
Sorry, i haven't accessed at this project anymore. :(

**Comment by jorgemarcondes** [comment]
But i ll consider this issue solved, thanks!
