### ISSUE TITLE
Make serverless-offline-sqs able to use python lambdas

### ISSUE THREAD

**Issue by jkieberking** [CoorpAcademy/serverless-plugins#39]
Would love to use this plugin, but we are creating our lambdas in python

**Comment by arae** [comment]
Same here. Please add support for python.

**Comment by godu** [comment]
it seems to work already
https://github.com/CoorpAcademy/serverless-plugins/blob/fc9658af45942169dd58f16945be875609eb25fd/packages/serverless-offline-sqs-integration/serverless.yml#L30-L38

because `serverless-offline` support [python](https://github.com/dherault/serverless-offline/tree/master/manual_test_python).

If you need some help, don't hesitate to reopen an issue.
